/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    IconBlog: typeof import('./src/components/icons/IconBlog.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconJuejin: typeof import('./src/components/icons/IconJuejin.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader.vue')['default']
  }
}
